### PR TITLE
replace site address with :80

### PR DESCRIPTION
**Pull request by thomasbeaudry**
you need :80 so you the system's caddy talk to your internal caddy

### CODE REVIEW

**Review by joshunrau — CHANGES_REQUESTED** [review]
We need the environment variable for reverse proxy setups (like what I have for the demo). Please change the `SITE_ADDRESS` variable in `.env.template` instead of hardcoding it here.

Also, I was under the impression that `:80` is just a shorthand for`localhost:80`? Are there some docs I can read to learn about the distinction that you found?

**Comment by gdevenyi** [comment]
:80 is not equivalent to localhost:80

The cicvmhost01 deployment was unable to function in a caddy-behind-caddy (system caddy + docker caddy) situation without making this change.

system caddy config was:
```
#Internal OpenDataCapture for human studies
http://odc.douglas.rtss.qc.ca {
        reverse_proxy http://localhost:5500
}
```

**Comment by joshunrau** [comment]
Okay I'll change this in the env file. We need a generic solution for this

**Comment by joshunrau** [comment]
> > Okay I'll change this in the env file. We need a generic solution for this
> 
> You mean that the SITE_ADDRESS will become the entire line in the caddyfile?

No, I mean I will change `localhost:80` to ` :80`.

**Comment by joshunrau** [comment]
This is now changed in the template

**Pull request closed without merging**
